[features]
seeds = false
skip-lint = false
[programs.localnet]
journalist = "CV1DphaGKtzK1mMskXjDhSGQAnaXEqtq2dqFYSnXMrJm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/martin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
